#!/usr/bin/env bash
# Speechy API Test Runner
# Usage: bash tests/api/run.sh
# Prerequisites: PostgreSQL running, PHP 8.0+ with pgsql extension
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LOG_DIR="${REPO_ROOT}/tests/logs"
LOG_FILE="${LOG_DIR}/api.log"

mkdir -p "${LOG_DIR}"

# ─── Add Homebrew Postgres to PATH if not already there ───────────────────
for pg_bin_dir in \
    /opt/homebrew/Cellar/postgresql@17/*/bin \
    /opt/homebrew/Cellar/postgresql@15/*/bin \
    /opt/homebrew/opt/postgresql@17/bin \
    /opt/homebrew/opt/postgresql@15/bin \
    /usr/local/lib/postgresql*/bin \
    /usr/lib/postgresql/*/bin; do
    if [[ -d "${pg_bin_dir}" ]] && [[ -x "${pg_bin_dir}/psql" ]]; then
        export PATH="${pg_bin_dir}:${PATH}"
        break
    fi
done
# Also allow override via PSQL env var
PSQL="${PSQL_BIN:-psql}"

# ─── Resolve PHP binary (prefer 8.x over any system 7.x) ─────────────────
resolve_php() {
    # Allow override via env
    if [[ -n "${PHP_BIN:-}" ]]; then
        echo "${PHP_BIN}"
        return
    fi
    # Try Homebrew first (macOS common path), then PATH
    for candidate in /opt/homebrew/bin/php /usr/local/bin/php php; do
        if command -v "${candidate}" >/dev/null 2>&1; then
            local v
            v=$("${candidate}" -r "echo PHP_MAJOR_VERSION;" 2>/dev/null)
            if [[ "${v}" -ge 8 ]]; then
                echo "${candidate}"
                return
            fi
        fi
    done
    # Fall back to whatever php is in PATH
    echo "php"
}
PHP="$(resolve_php)"
echo "Using PHP: ${PHP} ($("${PHP}" -r 'echo phpversion();' 2>/dev/null))"

# ─── Load shared env ──────────────────────────────────────────────────────
source "${REPO_ROOT}/tests/.env.test"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║     Speechy API Test Suite                  ║"
echo "╚══════════════════════════════════════════════╝"
echo "  DB:   ${TEST_DB_NAME}@${TEST_DB_HOST}:${TEST_DB_PORT}"
echo "  URL:  ${API_BASE_URL}"
echo ""

# ─── Paths ────────────────────────────────────────────────────────────────
LICENSING_DIR="${REPO_ROOT}/licensing"
CONFIG_PHP="${LICENSING_DIR}/config.php"
CONFIG_BACKUP="${LICENSING_DIR}/config.php.bak"
PHP_SERVER_PID=""

# ─── Cleanup trap ─────────────────────────────────────────────────────────
cleanup() {
    local exit_code=$?

    # Kill PHP dev server
    if [[ -n "${PHP_SERVER_PID}" ]]; then
        kill "${PHP_SERVER_PID}" 2>/dev/null || true
        wait "${PHP_SERVER_PID}" 2>/dev/null || true
    fi

    # Restore original config.php
    if [[ -f "${CONFIG_BACKUP}" ]]; then
        mv "${CONFIG_BACKUP}" "${CONFIG_PHP}"
        echo ""
        echo "  [teardown] config.php restored from backup"
    fi

    # Drop test DB
    PGPASSWORD="${TEST_DB_PASS}" "${PSQL}" \
        -h "${TEST_DB_HOST}" -p "${TEST_DB_PORT}" -U "${TEST_DB_USER}" \
        -c "DROP DATABASE IF EXISTS ${TEST_DB_NAME};" postgres \
        >> "${LOG_FILE}" 2>&1 || true
    echo "  [teardown] test database dropped"

    exit $exit_code
}
trap cleanup EXIT

# ─── Step 1: Create / reset test DB ───────────────────────────────────────
echo "[1/4] Setting up test database..."

PGPASSWORD="${TEST_DB_PASS}" "${PSQL}" \
    -h "${TEST_DB_HOST}" -p "${TEST_DB_PORT}" -U "${TEST_DB_USER}" \
    -c "DROP DATABASE IF EXISTS ${TEST_DB_NAME};" postgres \
    >> "${LOG_FILE}" 2>&1

PGPASSWORD="${TEST_DB_PASS}" "${PSQL}" \
    -h "${TEST_DB_HOST}" -p "${TEST_DB_PORT}" -U "${TEST_DB_USER}" \
    -c "CREATE DATABASE ${TEST_DB_NAME};" postgres \
    >> "${LOG_FILE}" 2>&1

# Run all migrations in order
for migration in "${LICENSING_DIR}/migrations/"*.sql; do
    PGPASSWORD="${TEST_DB_PASS}" "${PSQL}" \
        -h "${TEST_DB_HOST}" -p "${TEST_DB_PORT}" -U "${TEST_DB_USER}" \
        -d "${TEST_DB_NAME}" -f "${migration}" \
        >> "${LOG_FILE}" 2>&1
done
echo "     ✓ Migrations applied"

# ─── Step 2: Write test config ────────────────────────────────────────────
echo "[2/4] Writing test config.php..."

# Backup existing config if present
if [[ -f "${CONFIG_PHP}" ]]; then
    cp "${CONFIG_PHP}" "${CONFIG_BACKUP}"
fi

cat > "${CONFIG_PHP}" << PHPEOF
<?php
// AUTO-GENERATED BY tests/api/run.sh — DO NOT COMMIT
// Original is backed up as config.php.bak and restored on test exit.
return [
    'db' => [
        'host' => '${TEST_DB_HOST}',
        'port' => ${TEST_DB_PORT},
        'name' => '${TEST_DB_NAME}',
        'user' => '${TEST_DB_USER}',
        'pass' => '${TEST_DB_PASS}',
    ],
    'admin_api_key'       => '${ADMIN_API_KEY}',
    'base_url'            => '${API_BASE_URL}',
    'trial_duration_days' => 30,
    'onesignal' => [
        'app_id'     => '',
        'api_key'    => '',
        'from_name'  => 'Speechy Test',
        'from_email' => 'noreply@speechy-test.invalid',
    ],
];
PHPEOF

echo "     ✓ config.php written (backup at config.php.bak)"

# ─── Step 3: Start PHP dev server ─────────────────────────────────────────
echo "[3/4] Starting PHP dev server on port ${API_PORT}..."

"${PHP}" -S "127.0.0.1:${API_PORT}" "${LICENSING_DIR}/index.php" \
    >> "${LOG_FILE}" 2>&1 &
PHP_SERVER_PID=$!

# Wait for server to be ready (up to 10s)
for i in $(seq 1 20); do
    if curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:${API_PORT}/api/version/check?platform=macos" 2>/dev/null | grep -q "200\|400\|404"; then
        break
    fi
    sleep 0.5
done

# Final check
if ! kill -0 "${PHP_SERVER_PID}" 2>/dev/null; then
    echo "ERROR: PHP server failed to start. Check ${LOG_FILE}"
    exit 1
fi
echo "     ✓ Server running (PID ${PHP_SERVER_PID})"

# ─── Step 4: Run test files ────────────────────────────────────────────────
echo "[4/4] Running test cases..."

TOTAL_PASSED=0
TOTAL_FAILED=0
SUITE_EXIT=0

# Inline PHP runner for each test file — collects pass/fail counts
run_test_file() {
    local file="$1"
    local basename
    basename=$(basename "${file}")

    # Run test file, capture output
    PHP_OUTPUT=$(
        TEST_DB_NAME="${TEST_DB_NAME}" \
        TEST_DB_HOST="${TEST_DB_HOST}" \
        TEST_DB_PORT="${TEST_DB_PORT}" \
        TEST_DB_USER="${TEST_DB_USER}" \
        TEST_DB_PASS="${TEST_DB_PASS}" \
        API_BASE_URL="${API_BASE_URL}" \
        ADMIN_API_KEY="${ADMIN_API_KEY}" \
        "${PHP}" -r "
require '${SCRIPT_DIR}/lib/harness.php';
require '${file}';
\$s = suite_summary();
echo \"__SUMMARY__:\" . \$s['passed'] . \":\" . \$s['failed'] . \"\n\";
" 2>&1
    )

    # Print output (minus the summary line)
    echo "${PHP_OUTPUT}" | { grep -v '^__SUMMARY__:' || true; }

    # Extract counts
    local summary_line
    summary_line=$(echo "${PHP_OUTPUT}" | { grep '^__SUMMARY__:' || true; } | tail -1)
    if [[ -n "${summary_line}" ]]; then
        local passed failed
        passed=$(echo "${summary_line}" | cut -d: -f2)
        failed=$(echo "${summary_line}" | cut -d: -f3)
        TOTAL_PASSED=$((TOTAL_PASSED + passed))
        TOTAL_FAILED=$((TOTAL_FAILED + failed))
        if [[ "${failed}" -gt 0 ]]; then
            SUITE_EXIT=1
        fi
    else
        echo "  [ERROR] Could not parse summary from ${basename}"
        SUITE_EXIT=1
    fi

    echo "${PHP_OUTPUT}" >> "${LOG_FILE}"
}

for test_file in "${SCRIPT_DIR}/cases/"*.test.php; do
    run_test_file "${test_file}"
done

# ─── Summary ──────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════"
if [[ "${SUITE_EXIT}" -eq 0 ]]; then
    echo "  \033[32mAll tests passed\033[0m  ✓  ${TOTAL_PASSED} assertions"
else
    echo "  \033[31mSome tests FAILED\033[0m  ✗  Passed: ${TOTAL_PASSED}  Failed: ${TOTAL_FAILED}"
fi
echo "  Log: ${LOG_FILE}"
echo "════════════════════════════════════════════════"
echo ""

exit "${SUITE_EXIT}"
